package dao

type DeweyCategory struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

var DeweyCategories = []DeweyCategory{
	{Code: "000", Name: "Computer Science, Information & General Works"},
	{Code: "010", Name: "Bibliography"},
	{Code: "020", Name: "Library & Information Sciences"},
	{Code: "030", Name: "Encyclopedias & Books of Facts"},
	{Code: "050", Name: "Magazines, Journals & Serials"},
	{Code: "060", Name: "Associations, Organizations & Museums"},
	{Code: "070", Name: "News Media, Journalism & Publishing"},
	{Code: "080", Name: "Quotations"},
	{Code: "090", Name: "Manuscripts & Rare Books"},

	{Code: "100", Name: "Philosophy & Psychology"},
	{Code: "110", Name: "Metaphysics"},
	{Code: "120", Name: "Epistemology"},
	{Code: "130", Name: "Parapsychology & Occultism"},
	{Code: "140", Name: "Philosophical Schools of Thought"},
	{Code: "150", Name: "Psychology"},
	{Code: "160", Name: "Logic"},
	{Code: "170", Name: "Ethics"},
	{Code: "180", Name: "Ancient, Medieval & Eastern Philosophy"},
	{Code: "190", Name: "Modern Western Philosophy"},

	{Code: "200", Name: "Religion"},
	{Code: "210", Name: "Philosophy & Theory of Religion"},
	{Code: "220", Name: "The Bible"},
	{Code: "230", Name: "Christianity & Christian Theology"},
	{Code: "240", Name: "Christian Practice & Observance"},
	{Code: "250", Name: "Christian Pastoral Practice"},
	{Code: "260", Name: "Christian Organization & Worship"},
	{Code: "270", Name: "History of Christianity"},
	{Code: "280", Name: "Christian Denominations"},
	{Code: "290", Name: "Other Religions"},

	{Code: "300", Name: "Social Sciences"},
	{Code: "310", Name: "Statistics"},
	{Code: "320", Name: "Political Science"},
	{Code: "330", Name: "Economics"},
	{Code: "340", Name: "Law"},
	{Code: "350", Name: "Public Administration & Military Science"},
	{Code: "360", Name: "Social Problems & Social Services"},
	{Code: "370", Name: "Education"},
	{Code: "380", Name: "Commerce, Communications & Transportation"},
	{Code: "390", Name: "Customs, Etiquette & Folklore"},

	{Code: "400", Name: "Language"},
	{Code: "410", Name: "Linguistics"},
	{Code: "420", Name: "English & Old English Languages"},
	{Code: "430", Name: "German & Related Languages"},
	{Code: "440", Name: "French & Related Languages"},
	{Code: "450", Name: "Italian, Romanian & Related Languages"},
	{Code: "460", Name: "Spanish, Portuguese & Galician"},
	{Code: "470", Name: "Latin & Italic Languages"},
	{Code: "480", Name: "Classical & Modern Greek Languages"},
	{Code: "490", Name: "Other Languages"},

	{Code: "500", Name: "Science"},
	{Code: "510", Name: "Mathematics"},
	{Code: "520", Name: "Astronomy"},
	{Code: "530", Name: "Physics"},
	{Code: "540", Name: "Chemistry"},
	{Code: "550", Name: "Earth Sciences & Geology"},
	{Code: "560", Name: "Fossils & Prehistoric Life"},
	{Code: "570", Name: "Biology"},
	{Code: "580", Name: "Plants (Botany)"},
	{Code: "590", Name: "Animals (Zoology)"},

	{Code: "600", Name: "Technology"},
	{Code: "610", Name: "Medicine & Health"},
	{Code: "620", Name: "Engineering"},
	{Code: "630", Name: "Agriculture"},
	{Code: "640", Name: "Home & Family Management"},
	{Code: "650", Name: "Management & Public Relations"},
	{Code: "660", Name: "Chemical Engineering"},
	{Code: "670", Name: "Manufacturing"},
	{Code: "680", Name: "Manufacture for Specific Uses"},
	{Code: "690", Name: "Construction of Buildings"},

	{Code: "700", Name: "Arts & Recreation"},
	{Code: "710", Name: "Landscaping & Area Planning"},
	{Code: "720", Name: "Architecture"},
	{Code: "730", Name: "Sculpture, Ceramics & Metalwork"},
	{Code: "740", Name: "Drawing & Decorative Arts"},
	{Code: "750", Name: "Painting"},
	{Code: "760", Name: "Graphic Arts"},
	{Code: "770", Name: "Photography & Computer Art"},
	{Code: "780", Name: "Music"},
	{Code: "790", Name: "Sports, Games & Entertainment"},

	{Code: "800", Name: "Literature"},
	{Code: "810", Name: "American Literature in English"},
	{Code: "820", Name: "English & Old English Literatures"},
	{Code: "830", Name: "German & Related Literatures"},
	{Code: "840", Name: "French & Related Literatures"},
	{Code: "850", Name: "Italian, Romanian & Related Literatures"},
	{Code: "860", Name: "Spanish, Portuguese & Galician Literatures"},
	{Code: "870", Name: "Latin & Italic Literatures"},
	{Code: "880", Name: "Classical & Modern Greek Literatures"},
	{Code: "890", Name: "Other Literatures"},

	{Code: "900", Name: "History & Geography"},
	{Code: "910", Name: "Geography & Travel"},
	{Code: "920", Name: "Biography & Genealogy"},
	{Code: "930", Name: "History of Ancient World (to ca. 499)"},
	{Code: "940", Name: "History of Europe"},
	{Code: "950", Name: "History of Asia"},
	{Code: "960", Name: "History of Africa"},
	{Code: "970", Name: "History of North America"},
	{Code: "980", Name: "History of South America"},
	{Code: "990", Name: "History of Other Areas"},
}
